# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Scriptalicious
version:      1.14
version_from: lib/Scriptalicious.pm
installdirs:  site
requires:
    Term::ReadKey:                 0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
